###
post http://localhost:4000/person-api/person
Content-Type: application/json

{
    "firstname":"preethi",
    "lastname":"chowdary",
    "email":"jutlapreeethi@gmail.com",
    "password":"preethi",
    "dateofbirth":"26-02-2005",
    "phoneno":"9887654321",
    "gender":"female",
    "isdriver":"no"
}

###
post  http://localhost:4000/person-api/login
Content-Type: application/json

{
    "email":"jutlapreeethi@gmail.com",
    "password":"preethi"

}

###
post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userId":"{{$timestamp}}",
    "noofpassengers":"2",
    "phoneno":"9876543210",
    "pickup":"miyapur",
    "destination":"nizampet",
    "dateofride":"25-02-2024",
    "time":"8AM-12PM",
    "restrictions":"no smoking",
    "drivergender":"female"
}

###
post http://localhost:4000/driver-api/driver
Content-Type: application/json

{
    
    "noofseats":"2",
    "phoneno":"9876543210",
    "pickup":"miyapur20",
    "destination":"nizampet",
    "dateofride":"25-02-2024",
    "time":"8AM-12PM",
    "passengergender":"female"
}

###
post http://localhost:4000/driver-api/getdriver
Content-Type: application/json

{
    "noofpassengers":"2",
    "phoneno":"9876543210",
    "pickup":"kurnool",
    "destination":"hyderabad",
    "dateofride":"25-02-2024",
    "time":"8AM-12PM",
    "restrictions":"no smoking",
    "drivergender":"female"
}
###
post  http://localhost:4000/driver-api/confirm
Content-Type: application/json

{
    "driverId":"1722869929",
    "userId":"{{$timestamp}}",
    "noofpassengers":"2",
    "phoneno":"9876543210",
    "pickup":"miyapur2",
    "destination":"nizampet2",
    "dateofride":"25-02-2024",
    "time":"8AM-12PM",
    "restrictions":"no smoking",
    "drivergender":"female",
    "status":"false"

}
###
put http://localhost:4000/driver-api/accept
Content-Type: application/json

{
    "_id":"66b2275da939e7f4311a67a5",
    "driverId":"66b23a2c0741f2b152fb4956",
    "userId":"{{$timestamp}}",
    "noofpassengers":"2",
    "phoneno":"9876543210",
    "pickup":"miyapur2",
    "destination":"nizampet2",
    "dateofride":"25-02-2024",
    "time":"8AM-12PM",
    "restrictions":"no smoking",
    "drivergender":"female",
    "status":"false"

}


###
post  http://localhost:4000/driver-api/getuser
Content-Type: application/json

{
    "id":"66af69431787da57c94c543c"
    
}
###
get http://localhost:4000/driver-api/rideconfirmation

